"""Quickstart: auto-detect an agent framework and generate a LIFE FORGE harness.

This module powers the ``lifeforge quickstart`` command.  It inspects a
project directory, detects which agent framework (LangChain, LangGraph,
CrewAI, AutoGen, LlamaIndex, smolagents, OpenAI Agents SDK) the project is
built with, guesses module-level agent/executor definitions, writes a small
``lifeforge_harness.py`` that wraps the user's agent with the matching LIFE
FORGE adapter, and runs that harness to evaluate the agent.

Nothing here executes user code during detection: ``scan_directory`` only
reads text and ``find_agent_candidates`` only parses the AST.  Evaluation DOES
execute user code (the target file is imported and a class/factory target is
called), so it only happens with explicit consent (``--yes``); without it the
command prints what would run and stops, exactly like ``--dry-run``.  The
generated harness is the executable artifact and it degrades with a clear
error message when the selected framework or adapter cannot be imported.

All console output is plain ASCII with ``[TAG]`` prefixes, matching the style
used by :mod:`lifeforge.cli.main`.
"""
from __future__ import annotations

import argparse
import ast
import datetime
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

# Framework label -> import prefixes to look for.  A prefix that starts with
# "from " or "import " is matched as a plain substring; any other prefix must
# follow a from/import keyword on a token boundary, so e.g.
# "from langchain.agents import ..." is not misdetected as the OpenAI Agents
# SDK (prefix "agents").
FRAMEWORK_IMPORTS: dict[str, tuple[str, ...]] = {
    "langchain": (
        "from langchain",
        "import langchain",
        "langchain_core",
        "langchain_openai",
        "langchain_community",
    ),
    "langgraph": ("langgraph",),
    "crewai": ("from crewai", "import crewai"),
    "autogen": ("autogen",),
    "llama_index": ("llama_index", "from llama_index"),
    "smolagents": ("smolagents",),
    "openai_agents": ("agents",),
}

# Detection priority used to pick the target when several frameworks appear in
# one project.  Files without any detection rank after every listed framework.
FRAMEWORK_PRIORITY: tuple[str, ...] = (
    "langgraph",
    "langchain",
    "crewai",
    "autogen",
    "llama_index",
    "smolagents",
    "openai_agents",
)

# Framework label -> adapter class name exposed by lifeforge.adapters.  Labels
# without a built-in adapter produce a harness that fails with clear guidance.
ADAPTER_CLASS_BY_FRAMEWORK: dict[str, str] = {
    "langchain": "LangChainAdapter",
    "langgraph": "LangGraphAdapter",
    "crewai": "CrewAIAdapter",
}

# Directories that are never scanned for framework imports.
SKIP_DIRECTORIES: frozenset[str] = frozenset(
    {".venv", "venv", ".git", "__pycache__", "build", "dist", "node_modules"}
)

# Module-level call names that strongly suggest an agent/executor definition.
AGENT_CALL_NAMES: frozenset[str] = frozenset(
    {
        "create_react_agent",
        "create_openai_tools_agent",
        "create_tool_calling_agent",
        "AgentExecutor",
        "Agent",
        "Crew",
        "StateGraph",
        "CompiledGraph",
        "initialize_agent",
        "ReActAgent",
        "CodeAgent",
        "ToolCallingAgent",
    }
)

HARNESS_FILENAME: str = "lifeforge_harness.py"

HARNESS_TEMPLATE: str = '''"""LIFE FORGE harness generated by 'lifeforge quickstart'.

Framework : {framework}
Target    : {module}:{attribute}
Created   : {created}

This file was generated automatically.  Edit it freely; it is an ordinary
Python script.  Running it evaluates the wrapped agent with the LIFE FORGE
evolutionary engine and writes a Markdown report.

    python lifeforge_harness.py

If the framework adapter cannot be imported the script prints a clear error
and exits.  Nothing from the user project or the framework is imported at
module load time.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import pathlib
import sys

FRAMEWORK = "{framework}"
ADAPTER_CLASS = "{adapter_class}"
TARGET_MODULE = "{module}"
TARGET_ATTRIBUTE = "{attribute}"
CREATED = "{created}"
GENERATIONS = 30
SEED = 42
REPORT_OUT = "results/eval_report.md"


def _parse_args(argv):
    parser = argparse.ArgumentParser(description="LIFE FORGE quickstart harness")
    parser.add_argument("--generations", type=int, default=GENERATIONS)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--out", type=str, default=REPORT_OUT)
    return parser.parse_args(argv)

_ADAPTER_MODULES = {{
    "LangChainAdapter": "lifeforge.adapters.langchain",
    "LangGraphAdapter": "lifeforge.adapters.langgraph",
    "CrewAIAdapter": "lifeforge.adapters.crewai",
}}

_ADAPTER_KEYWORDS = {{
    "LangChainAdapter": "executor",
    "LangGraphAdapter": "app",
    "CrewAIAdapter": "crew",
}}


def _fail(message):
    print("[FAIL] " + message)
    raise SystemExit(2)


def _load_target_module():
    path = pathlib.Path(TARGET_MODULE)
    if not path.is_absolute():
        path = pathlib.Path(__file__).resolve().parent / path
    if not path.is_file():
        _fail("Target module not found: " + str(path))
    sys.path.insert(0, str(path.parent))
    spec = importlib.util.spec_from_file_location("lifeforge_quickstart_target", path)
    if spec is None or spec.loader is None:
        _fail("Could not build an import spec for: " + str(path))
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        _fail("Error while importing " + str(path) + ": " + repr(exc))
    if not hasattr(module, TARGET_ATTRIBUTE):
        _fail("Attribute '" + TARGET_ATTRIBUTE + "' not found in " + str(path))
    return getattr(module, TARGET_ATTRIBUTE)


def _resolve_target(target):
    """Instantiate classes and factory functions; keep framework objects as-is."""
    if isinstance(target, type):
        return target()
    if hasattr(target, "invoke") or hasattr(target, "kickoff") or hasattr(target, "execute_task"):
        return target
    if callable(target):
        return target()
    return target


def _wrap_target(target):
    if not ADAPTER_CLASS:
        _fail(
            "No built-in LIFE FORGE adapter exists for framework '" + FRAMEWORK + "'. "
            "Built-in adapters: langchain, langgraph, crewai. "
            "Wrap your agent manually as an AgentInterface "
            "(see examples/custom_agent_evaluation.py) and run: "
            "lifeforge eval --target <file.py:attribute>"
        )
    module_name = _ADAPTER_MODULES.get(ADAPTER_CLASS)
    keyword = _ADAPTER_KEYWORDS.get(ADAPTER_CLASS)
    if module_name is None or keyword is None:
        _fail("Unknown adapter class: " + ADAPTER_CLASS)
    try:
        adapter_module = importlib.import_module(module_name)
        adapter_cls = getattr(adapter_module, ADAPTER_CLASS, None)
        if adapter_cls is None:
            _fail(module_name + " does not define " + ADAPTER_CLASS)
        return adapter_cls(**{{keyword: target}}, name="quickstart-" + FRAMEWORK)
    except ImportError as exc:
        _fail(
            "Could not import " + ADAPTER_CLASS + " from " + module_name + ": " + str(exc) + ". "
            "Install the optional dependency, e.g. pip install 'lifeforge[" + FRAMEWORK + "]'."
        )


def main(argv=None):
    options = _parse_args(sys.argv[1:] if argv is None else argv)
    print("[RUN] Importing and executing " + TARGET_MODULE + " (module-level code runs; "
          "'" + TARGET_ATTRIBUTE + "' is instantiated/called if it is a class or factory).")
    target = _load_target_module()
    try:
        target = _resolve_target(target)
    except Exception as exc:
        _fail("Could not instantiate the target agent: " + repr(exc))
    try:
        agent = _wrap_target(target)
    except Exception as exc:
        _fail("Could not wrap the target agent: " + repr(exc))

    from lifeforge.evolution.engine import EvolutionEngine
    from lifeforge.reporting.analyzer import CausalAnalyzer
    from lifeforge.reporting.report import ReportGenerator
    from lifeforge.sandbox.world_state import WorldState

    seed_state = WorldState.default_purchasing_world()
    engine = EvolutionEngine(seed=options.seed)
    print("[RUN] Evaluating " + agent.name + " over " + str(options.generations) + " generations...")
    summary = engine.run(agent, seed_state, generations=options.generations)

    analyzer = CausalAnalyzer()
    diagnostics = analyzer.analyze(agent, summary, seed_state)
    report = ReportGenerator.generate_markdown(diagnostics)

    out_path = pathlib.Path(options.out)
    if not out_path.is_absolute():
        out_path = pathlib.Path(__file__).resolve().parent / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")

    print("[OK] Evaluations: " + str(summary.total_evaluations))
    print("[OK] Critical failures: " + str(summary.critical_failures_count))
    print("[OK] Report written to " + str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


@dataclass
class FrameworkDetection:
    """One framework import found in one Python file.

    Attributes
    ----------
    framework:
        Label from :data:`FRAMEWORK_IMPORTS` (e.g. ``"crewai"``).
    path:
        Path of the file, relative to the scanned root when possible.
    line:
        One-based line number of the first matching import.
    evidence:
        The matching source line (stripped, truncated for readability).
    """

    framework: str
    path: str
    line: int
    evidence: str


# ----------------------------------------------------------------------
# Directory / file scanning
# ----------------------------------------------------------------------


def _iter_python_files(root: Path, max_files: int) -> list[Path]:
    """Return up to ``max_files`` Python files under ``root``, deterministically ordered.

    Skipped directories come from :data:`SKIP_DIRECTORIES`.  Both directory
    and file names are sorted so repeated runs scan the same files in the same
    order.
    """
    files: list[Path] = []
    if not root.exists() or not root.is_dir():
        return files

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(
            name for name in dirnames if name not in SKIP_DIRECTORIES
        )
        for filename in sorted(filenames):
            if not filename.endswith(".py"):
                continue
            files.append(Path(dirpath) / filename)
            if len(files) >= max_files:
                return files
    return files


def _display_path(root: Path, file_path: Path) -> str:
    """Return ``file_path`` relative to ``root`` when possible, else as a string."""
    try:
        return str(file_path.relative_to(root))
    except ValueError:
        return str(file_path)


def _framework_rank(framework: str | None) -> int:
    """Priority index of a framework label; unknown labels and ``None`` rank last."""
    if framework is None:
        return len(FRAMEWORK_PRIORITY)
    try:
        return FRAMEWORK_PRIORITY.index(framework)
    except ValueError:
        return len(FRAMEWORK_PRIORITY)


def _line_matches_prefix(line: str, prefix: str) -> bool:
    """Return True when ``line`` imports the module named by ``prefix``.

    Prefixes that include the ``from``/``import`` keyword are matched as plain
    substrings.  Bare module prefixes must appear directly after ``from`` or
    ``import`` on a token boundary, so ``sub_agents``, ``crew = Crew(agents=[])``
    or ``from langchain.agents import Agent`` do not trigger a false detection.
    """
    if prefix.startswith(("from ", "import ")):
        return prefix in line
    pattern = r"\b(?:from|import)\s+" + re.escape(prefix) + r"(?!\w)"
    return re.search(pattern, line) is not None


def scan_directory(root: Path, *, max_files: int = 200) -> list[FrameworkDetection]:
    """Scan ``root`` for supported agent framework imports.

    Comments and blank lines are ignored.  At most one detection is reported
    per ``(framework, file)`` pair, keeping the first matching line.  Results
    are sorted by ``(framework, path, line)``.

    Parameters
    ----------
    root:
        Directory to scan.  A nonexistent path yields an empty list.
    max_files:
        Upper bound on the number of Python files read.
    """
    root_path = Path(root)
    detections: list[FrameworkDetection] = []
    seen: set[tuple[str, str]] = set()

    for file_path in _iter_python_files(root_path, max_files):
        try:
            text = file_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        display = _display_path(root_path, file_path)
        for line_number, raw_line in enumerate(text.splitlines(), start=1):
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            for framework, prefixes in FRAMEWORK_IMPORTS.items():
                if (framework, display) in seen:
                    continue
                for prefix in prefixes:
                    if _line_matches_prefix(raw_line, prefix):
                        seen.add((framework, display))
                        detections.append(
                            FrameworkDetection(
                                framework=framework,
                                path=display,
                                line=line_number,
                                evidence=stripped[:200],
                            )
                        )
                        break

    detections.sort(key=lambda detection: (detection.framework, detection.path, detection.line))
    return detections


# ----------------------------------------------------------------------
# AST candidate discovery
# ----------------------------------------------------------------------


def _call_name(func_node: ast.expr) -> str | None:
    """Return the simple name of a call target (``Name`` or ``Attribute``)."""
    if isinstance(func_node, ast.Name):
        return func_node.id
    if isinstance(func_node, ast.Attribute):
        return func_node.attr
    return None


def _assignment_targets(node: ast.stmt) -> list[str]:
    """Return the module-level names bound by an assignment node."""
    names: list[str] = []
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name):
                names.append(target.id)
    elif isinstance(node, ast.AnnAssign):
        if isinstance(node.target, ast.Name):
            names.append(node.target.id)
    return names


def _candidate_names_from_tree(tree: ast.Module) -> list[str]:
    """Collect high-confidence assignment names, then public module functions.

    High-confidence entries are module-level assignments whose value is a call
    to a known agent/executor factory, plus any module-level name literally
    called ``agent``.  Lower-confidence entries are public module-level
    functions (``def my_agent(...)``), which are often factories.
    """
    assignments: list[str] = []
    functions: list[str] = []
    seen: set[str] = set()

    def add(bucket: list[str], name: str) -> None:
        if name in seen:
            return
        seen.add(name)
        bucket.append(name)

    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = _assignment_targets(node)
            if not targets:
                continue
            value = node.value
            is_agent_call = False
            if isinstance(value, ast.Call):
                name = _call_name(value.func)
                if name in AGENT_CALL_NAMES:
                    is_agent_call = True
            for target in targets:
                if is_agent_call or target == "agent":
                    add(assignments, target)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            add(functions, node.name)

    return assignments + functions


def find_agent_candidates(path: Path) -> list[str]:
    """Find module-level names that look like agent/executor objects.

    Assignment candidates (high confidence) are returned before function
    candidates (lower confidence), deduplicated, formatted as
    ``"<path>:<name>"``.  Files with syntax errors return an empty list.
    """
    file_path = Path(path)
    try:
        source = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    try:
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return []

    return [f"{file_path}:{name}" for name in _candidate_names_from_tree(tree)]


def _candidate_names_for_file(file_path: Path) -> list[str]:
    """Like :func:`find_agent_candidates` but returns bare names for one file."""
    try:
        source = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    try:
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return []
    return _candidate_names_from_tree(tree)


# ----------------------------------------------------------------------
# Target selection
# ----------------------------------------------------------------------


def detect_target(root: Path) -> tuple[str | None, list[FrameworkDetection], list[str]]:
    """Pick the best agent spec under ``root``.

    Returns ``(best_spec, all_detections, all_candidates)`` where ``best_spec``
    is the first candidate from the file carrying the highest-priority
    framework detection (priority order: langgraph, langchain, crewai,
    autogen, llama_index, smolagents, openai_agents, then files with no
    detection).  ``best_spec`` is ``None`` when nothing was found.
    """
    root_path = Path(root)
    detections = scan_directory(root_path)

    file_paths = _iter_python_files(root_path, 200)
    framework_by_file: dict[str, str] = {}
    for detection in detections:
        current = framework_by_file.get(detection.path)
        if current is None or _framework_rank(detection.framework) < _framework_rank(current):
            framework_by_file[detection.path] = detection.framework

    ordered_files = sorted(
        file_paths,
        key=lambda file_path: (
            _framework_rank(framework_by_file.get(_display_path(root_path, file_path))),
            _display_path(root_path, file_path),
        ),
    )

    candidates: list[str] = []
    for file_path in ordered_files:
        display = _display_path(root_path, file_path)
        for name in _candidate_names_for_file(file_path):
            candidates.append(f"{display}:{name}")

    best_spec = candidates[0] if candidates else None
    return best_spec, detections, candidates


# ----------------------------------------------------------------------
# Harness generation
# ----------------------------------------------------------------------


def write_harness(root: Path, framework: str, spec: str, *, force: bool = False) -> Path:
    """Write ``lifeforge_harness.py`` under ``root`` for ``framework`` and ``spec``.

    ``spec`` must use the ``<path>:<attribute>`` format understood by
    :func:`lifeforge.sandbox.loader.load_agent_from_spec`.  An existing harness
    is never overwritten unless ``force`` is True.

    Raises
    ------
    ValueError
        When ``spec`` does not contain ``:``.
    FileExistsError
        When the harness already exists and ``force`` is False.
    """
    root_path = Path(root)
    if ":" not in spec:
        raise ValueError(
            f"Invalid agent spec '{spec}'. Expected the format 'path/to/file.py:attribute'."
        )

    module_part, attribute = spec.rsplit(":", 1)
    harness_path = root_path / HARNESS_FILENAME
    if harness_path.exists() and not force:
        raise FileExistsError(
            f"{harness_path} already exists. Re-run with --force to overwrite it."
        )

    source = HARNESS_TEMPLATE.format(
        framework=framework,
        adapter_class=ADAPTER_CLASS_BY_FRAMEWORK.get(framework, ""),
        module=module_part.replace("\\", "\\\\").replace('"', '\\"'),
        attribute=attribute,
        created=datetime.date.today().isoformat(),
    )

    harness_path.parent.mkdir(parents=True, exist_ok=True)
    harness_path.write_text(source, encoding="utf-8")
    return harness_path


# ----------------------------------------------------------------------
# Orchestration
# ----------------------------------------------------------------------


def _framework_for_spec(spec: str, detections: list[FrameworkDetection]) -> str:
    """Return the highest-priority framework detected in the spec's file, or ``""``."""
    file_part = spec.rsplit(":", 1)[0]
    frameworks = [d.framework for d in detections if d.path == file_part]
    if not frameworks:
        return ""
    return min(frameworks, key=_framework_rank)


def run_quickstart(
    root: Path,
    *,
    dry_run: bool = False,
    force: bool = False,
    scenarios: int = 30,
    seed: int = 42,
    out: str = "results/eval_report.md",
    yes: bool = False,
) -> int:
    """Detect a framework under ``root``, generate a harness, and evaluate the agent.

    Evaluating means importing the detected file (its module-level code runs)
    and calling the detected attribute when it is a class or factory. That is
    arbitrary code execution from the scanned project, so it only happens
    when ``yes`` is True; otherwise the run stops after detection exactly like
    ``dry_run`` and prints what would be executed.

    The evaluation runs the generated harness (which wraps the target in the
    framework adapter) in a subprocess, passing ``scenarios``/``seed``/``out``.

    Returns 0 on success (or on a detection-only run) and non-zero when
    nothing usable was detected or the evaluation failed.
    """
    root_path = Path(root)

    print("[DETECT] Scanning for agent frameworks under: " + str(root_path))
    best_spec, detections, candidates = detect_target(root_path)

    for detection in detections:
        print(
            "[DETECT] "
            + detection.framework
            + " | "
            + detection.path
            + ":"
            + str(detection.line)
        )

    if not detections and not candidates:
        print(
            "[FAIL] No supported agent framework or agent definition was detected under: "
            + str(root_path)
        )
        print("[FAIL] Supported frameworks: " + ", ".join(sorted(FRAMEWORK_IMPORTS)))
        print(
            "[GUIDE] For a hand-written agent, run: "
            "lifeforge eval --target <file.py:attribute>"
        )
        return 1

    if best_spec is None:
        print("[FAIL] Framework imports were detected but no agent/executor candidate was found.")
        print(
            "[GUIDE] Define a module-level name such as 'agent', a factory function, "
            "or an assignment like 'executor = AgentExecutor(...)'."
        )
        return 1

    framework = _framework_for_spec(best_spec, detections)
    if not framework:
        print("[FAIL] Found an agent candidate but no supported framework import in its file: " + best_spec)
        print("[FAIL] Supported frameworks: " + ", ".join(sorted(FRAMEWORK_IMPORTS)))
        print("[GUIDE] Evaluate it directly with: lifeforge eval --target " + best_spec)
        return 1

    print("[CONFIGURE] Framework: " + framework)
    print("[CONFIGURE] Target spec: " + best_spec)

    harness_path = root_path / HARNESS_FILENAME
    spec_module, spec_attribute = best_spec.rsplit(":", 1)
    spec_path = Path(spec_module)
    if not spec_path.is_absolute():
        spec_path = (root_path / spec_path).resolve()

    print(
        "[NOTICE] Evaluating will IMPORT AND EXECUTE " + str(spec_path)
        + ": its module-level code runs with your permissions, and '" + spec_attribute
        + "' is instantiated/called if it is a class or factory function. Tools bound "
        "inside the framework agent may also run for real."
    )

    if dry_run:
        print(
            "[CONFIGURE] Dry run: skipping harness generation ("
            + str(harness_path)
            + ") and evaluation."
        )
        return 0

    if not yes:
        print(
            "[CONFIGURE] Not executing without consent: re-run with --yes to write "
            + str(harness_path)
            + " and run the evaluation. Nothing was written or executed."
        )
        return 0

    try:
        written = write_harness(root_path, framework, best_spec, force=force)
    except FileExistsError as exc:
        print("[FAIL] " + str(exc))
        return 1
    print("[CONFIGURE] Harness written: " + str(written))

    out_path = Path(out)
    if not out_path.is_absolute():
        out_path = root_path / out_path

    print(
        "[RUN] Starting LIFE FORGE evaluation via the harness ("
        + str(scenarios)
        + " generations, seed "
        + str(seed)
        + ")..."
    )

    # The harness wraps the target in the framework adapter; it runs in its
    # own interpreter so the user's module (and any sys.exit it performs)
    # cannot take down or pollute this process.
    command = [
        sys.executable,
        str(written),
        "--generations",
        str(int(scenarios)),
        "--seed",
        str(int(seed)),
        "--out",
        str(out_path),
    ]
    sys.stdout.flush()
    try:
        completed = subprocess.run(command, cwd=str(root_path), check=False)
    except (OSError, KeyboardInterrupt) as exc:
        print("[FAIL] Evaluation could not be started: " + repr(exc))
        return 1

    if completed.returncode != 0:
        print("[FAIL] Evaluation failed (harness exit code " + str(completed.returncode) + ").")
        return completed.returncode if completed.returncode > 0 else 1

    print("[OK] Quickstart complete. Report: " + str(out_path))
    return 0


# ----------------------------------------------------------------------
# CLI wiring (called from lifeforge.cli.main)
# ----------------------------------------------------------------------


def add_quickstart_parser(subparsers: argparse._SubParsersAction) -> argparse.ArgumentParser:
    """Register the ``quickstart`` subcommand and return its parser."""
    parser = subparsers.add_parser(
        "quickstart",
        help="Auto-detect an agent framework, generate a harness, and evaluate it",
        description=(
            "Scan a directory for a supported agent framework, generate "
            "lifeforge_harness.py around the detected agent, and run the LIFE FORGE "
            "evolutionary evaluation."
        ),
    )
    parser.add_argument(
        "--path",
        type=str,
        default=".",
        help="Directory to scan for agent frameworks (default: current directory)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Detect and report only; write no harness and run no evaluation",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing lifeforge_harness.py",
    )
    parser.add_argument(
        "--scenarios",
        type=int,
        default=30,
        help="Number of evolutionary generations (default: 30)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for deterministic exploration (default: 42)",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="results/eval_report.md",
        help="Output markdown report path",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Consent to importing and executing the detected agent file (required to evaluate)",
    )
    parser.set_defaults(func=cmd_quickstart)
    return parser


def cmd_quickstart(args: argparse.Namespace) -> int:
    """CLI entry point: run the quickstart flow from parsed arguments."""
    return run_quickstart(
        Path(getattr(args, "path", ".") or "."),
        dry_run=bool(getattr(args, "dry_run", False)),
        force=bool(getattr(args, "force", False)),
        scenarios=int(getattr(args, "scenarios", 30)),
        seed=int(getattr(args, "seed", 42)),
        out=str(getattr(args, "out", "results/eval_report.md")),
        yes=bool(getattr(args, "yes", False)),
    )
